name: Docker Image CI

on:
  release:
    types: [ published ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.DOCKER_HUB_REPOSITORY }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          INSTALL_PYTHON_VERSION: 3.8
          INSTALL_NODE_VERSION: 12
        with:
          context: .
          push: true
          tags: $DOCKERHUB_USERNAME/$REPOSITORY_NAME:latest, $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ github.event.release.tag_name }}
